version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    
